import os

# zwift-client bundles a protobuf message file generated by an old protoc (<3.19) that
# constructs descriptors directly (_descriptor.FieldDescriptor(...)); modern protobuf
# runtimes reject that ("Descriptors cannot be created directly") unless forced into the
# pure-Python implementation. Must be set before anything imports google.protobuf.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

from zwift import Client
from zwift.error import RequestException
from paho.mqtt import client as mqtt
from power_to_color import PowerToColor
from settings import *
import logging
import signal
import time
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _handle_sigterm(signum, frame):
    """Translate SIGTERM (sent by e.g. systemctl stop/restart) into a KeyboardInterrupt,
    so it goes through the same graceful shutdown path as Ctrl+C instead of killing the
    process outright and skipping the LED shutoff."""
    raise KeyboardInterrupt()


def setup_mqtt():
    """Setup and configure the MQTT client."""
    try:
        mqtt_client = mqtt.Client(protocol=mqtt.MQTTv5)
        mqtt_client.username_pw_set(MQTT_LOGIN, MQTT_PW)
        mqtt_client.will_set(MQTT_ENABLE_ALL_TOPIC, payload="Offline", retain=True)
        mqtt_client.connect(MQTT_HOST_NAME, keepalive=MQTT_KEEPALIVE_SECONDS)
        mqtt_client.publish(MQTT_ENABLE_ALL_TOPIC, payload="Online", retain=True)
        logger.info(f"MQTT client successfully connected to {MQTT_HOST_NAME}")
        return mqtt_client
    except Exception as e:
        logger.error(f"MQTT client could not connect to {MQTT_HOST_NAME}, check settings.py ({e})")
        exit(1)


def publish_status(mqtt_client, topic, payload):
    """Publish status to the MQTT broker."""
    if USE_MQTT:
        mqtt_client.publish(topic, payload, retain=False)


def main():
    signal.signal(signal.SIGTERM, _handle_sigterm)
    mqtt_client = None

    if USE_MQTT:
        mqtt_client = setup_mqtt()

    client = Client(USERNAME, PASSWORD)
    world = client.get_world(1)

    try:
        profile = client.get_profile()
        user_profile = profile.profile
        ftp_user_profile = int(user_profile["ftp"])
        if ftp_user_profile <= 0:
            raise ValueError(f"FTP must be a positive number, got {ftp_user_profile}")
        logger.info(f'Login {PLAYER_ID}, user {USERNAME}, ftp {ftp_user_profile} - successfully done')
    except (Exception, RequestException) as e:
        logger.error(f'Error retrieving user profile, please check username, password and PLAYER_ID in settings.py ({e})')
        exit(1)

    online = False
    error_count = 0
    color_mapper = PowerToColor(THRESHOLDS, DEADBAND, OVERRUN_LIMIT)

    try:
        while not online:
            if USE_MQTT:
                mqtt_client.loop_start()

            try:
                world.player_status(PLAYER_ID)
                online = True
                error_count = 0
                logger.info(f'{PLAYER_ID} appears to be online, lets retrieve activity data - trying..')
                if USE_MQTT:
                    publish_status(mqtt_client, MQTT_ENABLE_ALL_TOPIC, 1)
                    publish_status(mqtt_client, MQTT_DIMMER_TOPIC, 100)
            except (Exception, RequestException) as e:
                online = False
                error_count += 1
                logger.info(f'{PLAYER_ID} appears to be offline - trying.. {error_count} ({e})')
                if USE_MQTT:
                    publish_status(mqtt_client, MQTT_ENABLE_ALL_TOPIC, 0)
            time.sleep(MQTT_CONNECT_RETRY_INTERVAL)

            while online:
                try:
                    status = world.player_status(PLAYER_ID)
                    if status.sport == 0:
                        power_percentage = round(status.power / ftp_user_profile * 100)
                        led_color_hex = color_mapper.switch_output(power_percentage)
                        msg_dict = {
                            'is_online': 1,
                            'sport': 'cycling',
                            'hr': status.heartrate,
                            'power': status.power,
                            'power percentage': power_percentage,
                            'rbg output color': led_color_hex,
                            'speed': float(f"{float(status.speed) / 1000000.0:.2f}")
                        }
                        logger.info(msg_dict)

                        if USE_MQTT:
                            publish_status(mqtt_client, MQTT_BASE_COLOR_TOPIC, led_color_hex)
                            publish_status(mqtt_client, MQTT_INFO_TOPIC, payload=json.dumps(msg_dict))
                except (Exception, RequestException) as e:
                    online = False
                    logger.info(f'{PLAYER_ID} appears to have gone offline ({e})')

                time.sleep(MQTT_ZWIFT_REQUEST_INTERNAL)

            if USE_MQTT:
                mqtt_client.loop_stop()
            time.sleep(MQTT_CONNECT_RETRY_INTERVAL)
    except KeyboardInterrupt:
        logger.info("Shutting down...")
    finally:
        if USE_MQTT and mqtt_client is not None:
            mqtt_client.loop_start()
            publish_status(mqtt_client, MQTT_ENABLE_ALL_TOPIC, 0)
            time.sleep(0.3)
            mqtt_client.loop_stop()
            mqtt_client.disconnect()


if __name__ == "__main__":
    main()
